#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

case $1 in
    ''|*[!0-9]*) "$adr_bin_dir/adr-list" | grep "$1" | head -1
    ;;
    *) "$adr_bin_dir/adr-list" | grep "/0*$1" | head -1
    ;;
esac
